- anat: /bids_dataset/sub-0025427/ses-1/anat/sub-0025427_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: /bids_dataset/sub-0025427/ses-1/func/sub-0025427_ses-1_task-rest_run-1_bold.nii.gz
  site_id: site-none
  subject_id: sub-0025427
  unique_id: ses-1